### ISSUE TITLE
Add pop-up card widget for reading a blog

### ISSUE THREAD

**Issue by vedantbahel** [vedantbahel/viteED#23]
As it can be seen in the proposed UI in the readme file, when the user open any mini-blog, it should open the blog content as a pop-up with certain options. 
If you can work on this UI, please reply here.

**Comment by chandansgowda** [comment]
Hey @vedantbahel 
Recently came across this project. I would like to take up this work.

**Comment by vedantbahel** [comment]
Done. Thank you and good luck!

**Comment by chandansgowda** [comment]
Hey @vedantbahel,
Since I got some emergency work, I couldn't work much on the project this weekend. I have worked on the UI using static data. I'll refactor it and create a pull request by tomorrow's EOD.
![image](https://user-images.githubusercontent.com/41890434/180656521-d8141a6b-759c-4522-9bba-96e51d146881.png)

**Comment by chandansgowda** [comment]
Hey @vedantbahel 
I have added the required popup display card widget for reading blogs. Kindly check my pull request #27
Thank You
